// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNIcIltgdMDWAU1G7PEVKV-fO-GDC8Vuw',
    appId: '1:269447498129:web:435e47eb9d40a645317230',
    messagingSenderId: '269447498129',
    projectId: 'chat--app-4031a',
    authDomain: 'chat--app-4031a.firebaseapp.com',
    storageBucket: 'chat--app-4031a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqLS_mxPxjZXdqOPJy9Tpzpt6gi2Pvt-o',
    appId: '1:269447498129:android:d973d082a9d33d10317230',
    messagingSenderId: '269447498129',
    projectId: 'chat--app-4031a',
    storageBucket: 'chat--app-4031a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA03Gj9V96IpbgmGOYwAxeDIqaggu6uqM0',
    appId: '1:269447498129:ios:7c6d9e76b5b0b4e4317230',
    messagingSenderId: '269447498129',
    projectId: 'chat--app-4031a',
    storageBucket: 'chat--app-4031a.firebasestorage.app',
    iosBundleId: 'com.example.scholarChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA03Gj9V96IpbgmGOYwAxeDIqaggu6uqM0',
    appId: '1:269447498129:ios:7c6d9e76b5b0b4e4317230',
    messagingSenderId: '269447498129',
    projectId: 'chat--app-4031a',
    storageBucket: 'chat--app-4031a.firebasestorage.app',
    iosBundleId: 'com.example.scholarChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNIcIltgdMDWAU1G7PEVKV-fO-GDC8Vuw',
    appId: '1:269447498129:web:49599c53c2cbee8e317230',
    messagingSenderId: '269447498129',
    projectId: 'chat--app-4031a',
    authDomain: 'chat--app-4031a.firebaseapp.com',
    storageBucket: 'chat--app-4031a.firebasestorage.app',
  );

}